services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: ${PROJECT_PREFIX}_zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.6-debian-11
    container_name: ${PROJECT_PREFIX}_kafka
    ports:
      - "9092:9092"
    restart: unless-stopped
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
      - KAFKA_CFG_MESSAGE_MAX_BYTES=20000000
    depends_on:
      - zookeeper
    networks:
      - default
      - backend_network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: ${PROJECT_PREFIX}_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_READONLY=false

  supervisor:
    container_name: ${PROJECT_PREFIX}_supervisor
    build:
      context: ./containers/php
      dockerfile: ./WorkerDockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        APP_ENV: "$APP_ENV"
    volumes:
      - ./../:/var/www/html
    depends_on:
      - kafka
    links:
      - php
      - kafka
    restart: unless-stopped
    networks:
      - default
      - backend_network

networks:
  backend_network:
    external: true
  sail:
    driver: bridge